name: ci

on:
  push:
    branches:
      - 'main'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: "ghcr.io/0xffea/demo-fractal-api:latest"
  IMAGE_NAME_COMPUTE: "ghcr.io/0xffea/demo-fractal-compute:latest"

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: api
          platforms: linux/amd64
          push: true
          tags: ${{ env.IMAGE_NAME }}
      -
        name: Build and push compute
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: compute
          platforms: linux/amd64
          push: true
          tags: ${{ env.IMAGE_NAME_COMPUTE }}
      -
        name: Inspect
        run: |
          docker buildx imagetools inspect ${{ env.IMAGE_NAME }}
